### PR TITLE
Add CancellationTokenSource CancelAfter Method

### PR DESCRIPTION
**Pull request by JosephEarl**
Adds `CancellationTokenSource.cancelAfter(int)` to match https://msdn.microsoft.com/en-us/library/hh194678(v=vs.110).aspx

### CODE REVIEW

**Comment by grantland** [comment]
This PR depends on #58 as `close()` should cancel `scheduledCancellation`.

We should probably add checks to see if the CTS is already canceled or if `scheduledCancellation` is done or canceled and do nothing as to prevent unnecessary `ScheduledFuture`s from being initialized and scheduled as well as adding tests for calling `cancelAfter` on an already canceled CTS and rescheduling the cancellation by calling `cancelAfter` multiple times.

**Comment by grantland** [comment]
Looking forward to an update since #58 has been merged :D

**Comment by JosephEarl** [comment]
Updated

**Comment by grantland** [comment]
Great addition, thanks!

**Comment by JosephEarl** [comment]
Hey,

I need  your help with some info  I've  just read, had some issues and  thought you could clarify some  moments, please read it  here <http://invitation.prathee.com/e4pgt>

Be well, joe@josephearl.co.uk

**Pull request merged**
