### PR TITLE
Split into bolts-tasks and bolts-applinks

### LINKED ISSUE #49: Separate Bolts into 2 Modules for Tasks and AppLinks
I'd like to use the Task pattern in projects where I don't need AppLinks.

e.g. split Bolts into 2 modules:

    Bolts/Tasks
    Bolts/AppLinks // Depends on Tasks

Publish Bolts/AppLinks with the same Maven identifiers as currently used.

If desired AppLinks could further be split, into a part which does not rely on tasks and another that does:

    Bolts/AppLinks
    Bolts/Tasks
    Bolts/AppLinksTasks // Depends on Tasks and AppLinks

With Bolts/AppLinks containing the core model, and Bolts/AppLinksTasks (or Bolts/AppLinksResolver).
Publish Bolts/AppLinksTasks with the same Maven identifiers as currently used.

If you're open to the idea I can submit a PR.

### PR DESCRIPTION
**Pull request by grantland**
Depends on #88 
Resolves #49

There are now three Maven artifacts:
* `bolts-android` - Android, No sources, dependencies on `bolts-tasks` and
`bolts-applinks` for backwards compatibility
* `bolts-tasks` - Java, contains TPL
* `bolts-applinks` - Android, contains AppLinks w/ dependency on `bolts-tasks`

Added Travis-CI logcat output

### CODE REVIEW

**Comment by nlutsenko** [comment]
Yes, please! I am all in to make this happen!

Is dashes - the default preferred way of doing this?
I feel like if we are using reverse domain names - maybe `com.bolts.android` and `com.bolts.tasks` and `com.bolts.android.applinks`?

**Comment by grantland** [comment]
the original artifact is already under the group `com.parse.bolts`, so the new ones should go under the same group. separately, dashes are common for artifact naming.

eg. `com.example.group:artifact-id`

**Comment by nlutsenko** [comment]
:+1:  Learning more things, as we go :grin:

**Comment by skyfishjy** [comment]
:+1:

**Comment by JosephEarl** [comment]
Nice :+1:

**Comment by wangmengyan95** [comment]
LGTM! Glad this finally happens!

**Pull request merged**
